admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }
static_resources:
  strategies:
  - name: ctp_preinsert
    strategy: { mode: prod_bcqh_ctp_mini_tele }
    ctp:
    - debug_ntr_simnow: { 
      trade_addr: tcp://180.168.146.187:10101,
      md_addr: tcp://180.168.146.187:10111,
      user_id: 143292,
      password: wangfeng123,
      broker_id: 9999,
      auth_code: J68D3TN4TYCP1ES7,
      product_info: client_fhsoft,
      app_id: client_fhsoft_1.0.0
      }
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 10000 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        typed_config:
          @type: type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: [*]
              routes:
              - match: { prefix: / }
                route: { host_rewrite: www.baidu.com, cluster: service_baidu }
          http_filters:
          - name: envoy.router
  clusters:
  - name: service_baidu
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: service_baidu
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.baidu.com
                port_value: 80
    tls_context:
      sni: www.baidu.com