# Azure Pipelines
trigger:
- master

jobs:
- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'

  steps:
  - bash: mkdir $(Pipeline.Workspace)/bazel-out

  - task: CacheBeta@0
    inputs:
      key: .bazelversion | "$(Agent.OS)" | "$(Build.SourceBranch)" | "$(Build.BuildNumber)"
      restoreKeys: |
        .bazelversion | $(Agent.OS) | "$(Build.SourceBranch)"
        .bazelversion | $(Agent.OS) | "$(System.PullRequest.TargetBranch)"
        .bazelversion | $(Agent.OS) | "refs/heads/master"
      path: $(Pipeline.Workspace)/bazel-out
    continueOnError: true

  - script: ./ci/mac_ci_setup.sh
    displayName: 'Install dependencies'

  - script: ./ci/mac_ci_steps.sh
    displayName: 'Run Mac CI'
    env:
      BAZEL_STARTUP_OPTIONS: --output_base=$(Pipeline.Workspace)/bazel-out
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/bazel-testlogs/**/test.xml'
      testRunTitle: 'macOS'
    condition: always()
