# Azure Pipelines
trigger:
- master

jobs:
- job: macOS
  timeoutInMinutes: 360
  pool:
    vmImage: 'macos-latest'

  steps:
  - script: ./ci/mac_ci_setup.sh
    displayName: 'Install dependencies'

  - script: ./ci/mac_ci_steps.sh
    displayName: 'Run Mac CI'
    env:
      BAZEL_REMOTE_CACHE: grpcs://remotebuildexecution.googleapis.com
      BAZEL_REMOTE_INSTANCE: projects/envoy-ci/instances/default_instance
      BAZEL_BUILD_EXTRA_OPTIONS: "--announce_rc --curses=no --nodistinct_host_configuration --build_tests_only"
      GCP_SERVICE_ACCOUNT_KEY: $(GcpServiceAccountKey)

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/bazel-testlogs/**/test.xml'
      testRunTitle: 'macOS'
    condition: always()
